#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

MYSQL_IMAGE="mysql"
MYSQL_IMAGE_VERSION=5.7
MYSQL_ROOT=/var/lib/dokku/services/mysql

PLUGIN_DATA_ROOT=$MYSQL_ROOT
PLUGIN_SERVICE="MySQL"
PLUGIN_IMAGE=$MYSQL_IMAGE
PLUGIN_IMAGE_VERSION=$MYSQL_IMAGE_VERSION

if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q $PLUGIN_IMAGE_VERSION ; then
  docker pull $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION
fi

mkdir -p $PLUGIN_DATA_ROOT || echo "Failed to create $PLUGIN_SERVICE directory"
chown dokku:dokku $PLUGIN_DATA_ROOT
